version: '3.9'
services:
  reader-frontoffice:
    build: ./
    volumes:
      - ..:/usr/src/app
    ports:
      - "3211:3211"
    command: npm run dev
    networks:
      - backend

networks:
  backend:
    name: laradock_backend
    external: true